title: 202 ecommerce Security Advisories
description: Knowledge Base and CVE about PrestaShop modules security issues

# theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

collections:
- CVE_datas
